#!/usr/bin/env node

// babel's cli option --copy-files will override the --ignore setting
// so copy resources like this
require('fs-extra').copy(
  process.argv.slice(-2).shift(), 
  process.argv.slice(-2).pop(), 
  { filter: (src,dist)=>{ return (src.match(/\.js|\.jsx|stories|test/)===null)} },
  err => { if (err) return console.error (err); console.log ('Copy success!'); 
});